version: 2.1
jobs:
  unit-test:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout
      - run:
          name: "Unit Test"
          command: mvn test

workflows:
  ci:
    jobs:
      - unit-test